config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :adherents
end

app/models/adherent.rb
class Adherent < ApplicationRecord
  has_one :info_adherent
  has_one :social_adherent
  has_one :fiscal_adherent
  has_one :documents_adherent
  has_one :membre_adherent
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/documents_adherent.rb
class DocumentsAdherent < ApplicationRecord
  belongs_to :adherents
end

app/models/fiscal_adherent.rb
class FiscalAdherent < ApplicationRecord
  belongs_to :adherents
end

app/models/info_adherent.rb
class InfoAdherent < ApplicationRecord
  belongs_to :adherents

  validates :nom, presence: true
  validates :prenom, presence: true

  validates :telephone, presence: true
  validates :mail, presence: true

  validates :adresse, presence: true
  validates :codepostal, presence: true
  validates :ville, presence: true
end

app/models/membre_adherent.rb
class MembreAdherent < ApplicationRecord
  belongs_to :adherents
end

app/models/social_adherent.rb
class SocialAdherent < ApplicationRecord
  belongs_to :adherents
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/adherents_controller.rb
class AdherentsController < ApplicationController
  def index
    @adherents = Adherent.all
  end

  def show
    @adherent = Adherent.find(params[:id])
  end

  def new
    @adherent = Adherent.new
  end

  def create
    @adherent = Adherent.new(params[:adherent])
    if @adherent.save
      @adherent_info.save
      flash[:success] = "Object successfully created"
      redirect_to @adherent
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  def edit
    @adherent = Adherent.find(:id)
  end

  def update
    @adherent = Adherent.find(params[:id])
    if @adherent.update_attributes(params[:adherent])
      flash[:success] = "Object was successfully updated"
      redirect_to @adherent
    else
      flash[:error] = "Something went wrong"
      render 'edit'
    end
  end

  def destroy
    @adherent = Adherent.find(params[:id])
    if @adherent.destroy
      flash[:success] = 'Object was successfully deleted.'
      redirect_to adherents_path
    else
      flash[:error] = 'Something went wrong'
      redirect_to pages_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @navbar = true
    if user_signed_in?
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/adherents/index.html.erb
<div class="main">
    <h1>Gestion des étudiants</h1>
    <%= link_to new_adherent_path do %>
        <div> Nouveau Adhérent <i class="fas fa-plus-circle"></i></div>
    <% end %>
</div>

app/views/adherents/new.html.erb
<div class="main">
    <div class="container">
    <%= simple_form_for(@adherent) do |f| %>
        <%= f.input :prenom %>
        <%= f.input :nom %>
        <%= f.input :mail, placeholder: 'user@domain.com' %>
        <%= f.input :telephone, placeholder: '+33 6 99 99 99 99' %>
        <%= f.input :adresse, placeholder: '48 rue de varenne' %>
        <%= f.input :codepostal, placeholder: '75007' %>
        <%= f.input :ville, placeholder: 'Paris' %>
        <%= f.input :master, as: :boolean, checked_value: true, unchecked_value: false %>
        <%= f.submit %>
    <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Piotr - By HEX Agency</title>
    <%= favicon_link_tag asset_path('HEX-FondBlanc-Bleu.png')%>
    <meta property="og:url" content="http://www.hex-agency.fr" />
    <meta property="og:title" content="HEX Agency - Booster les J.E." />
    <meta property="og:description" content="Nous accompagnons les Junior-Entreprises dans la construction d’une image de marque professionnelle et dans l’optimisation de leur performance. " />
    <meta property="og:image" content=<%= asset_path('HEX-FondBlanc-Bleu.png') %> />
    <meta property="og:type" content="website" />

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <style>
      @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
      @import url('https://fonts.googleapis.com/css2?family=Manrope:wght@700&family=Poppins:ital,wght@0,700;1,700&display=swap');
    </style>
    <script src="https://kit.fontawesome.com/d79b5b6f74.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render 'shared/sidebar' %>
    <% else %>
      <% if @navbar == true %>
        <%= render 'shared/navbar' %>
      <% end %>
    <% end %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<% if user_signed_in? %>
    <div class="main">
        <h1>Suivi des études en cours</h1>
    </div>

<% else %>

    <div class="homecontainer">
        <div class="BoosterLesJE">
            <div class="divTexte">
                <div class="texte">
                    <div class="title">Booster les J.E. 🚀</div>
                    <div class="description">Nous accompagnons les Junior-Entreprises dans la construction d’une image de marque professionnelle et dans l’optimisation de leur performance. </div>
                    <div class="btn-1"><div class="txt">J'accélère !</div></div>
                </div>
            </div>
            <div class="divForme">
                <div class="form4"><div class="form"><%= render 'components/multipleforms' %></div></div>
                <div class="form1"><div class="form"><%= render 'components/form1' %></div></div>
                <div class="form2"><div class="form"><%= render 'components/form2' %></div></div>
                <div class="form3"><div class="form"><%= render 'components/form3' %></div></div>
            </div>
        </div>
    </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbardiv">
    <div class="logo"><%= render 'components/logo2' %></div>
    <div class="links">
        <a class="link" href="http://www.hex-agency.fr">Pour en apprendre plus sur HEX et nos service, rendez-vous sur notre site !</span>
    </div>
    <div class="btn-1"><%= link_to "Poste Vision", new_user_session_path, class: "txt"%></div>
</div>

app/views/shared/_sidebar.html.erb
<div class="sidenav">
  <div class="head">
    <%= render 'components/logo' %>
  </div>

  <div class="content">
    <a href="#"><div class="MainAction">Ressources Humaines</div></a>
    <a href="adherents"><div class="SecAction">Gestion Etudiants</div></a>
    <a href="#"><div class="SecAction">Gestion Intervenants</div></a>
    <a href="#"><div class="MainAction">Relations Clients</div></a>
    <a href="#"><div class="SecAction">Gestion Etudes</div></a>
  </div>



  <div class="foot">
    <div><%= link_to "Mon Compte", "#", :class => 'deco'%></div>
    <div><%= link_to "Déconnexion", destroy_user_session_path, method: :delete, :class => 'deco'%></div>
  </div>
</div>